from Bio.Data import CodonTable

def solve():
    protein = 'MDLHKDAVCENRYEELNLRAMHTPYMFRKTSQYRIEMQYVLEDGWMANWRLPRFWPHVLFVQPFCTHPLDHMYCNVGKLQDELTVFWYLKKYVKRPPRDDSDLQKQQNHEMKCCAMLQAHPSYASPYGGLGIWDEREINPQWLWNFDMTNCVNFNWYHYLIQTVYNTQAQTQSPSKRHFQCRHAKVIFLLSGKFVWYDNYNELHNGRFEMIFKSTFFIAGGMMAWPYGKMFLWGAHEPWRIMYEEDNKHEAAEGFPALPQCCLWIYRHDGLKVDSFISMNYYADDTEFWYHKHKNSYTVPSKFACKGPFCWIDEWNQRVTVCKVINAYMEDEAPTQYSWRWEYECKRTSKTIYQNACRKAEHCTCLTSLTMYDRYWTNDAPWYWRKENDEKMDGESSWDFRIFFPHCTIGFWPSWKWQGFNCKWMIQETTAHYDNMWEQGDFWCTLLKICTHMWTMFRTCMVNHPEIIWYRFVWMFMLYPIIFAFCQMIGAFGTFNTIHYGQANSVYKETDDKIDCFLEGSWCATEPPAQEKDILLHCVHCVRTTPDSSKNDPPWTSNYNIRREMLNHWWDESITCNEYNQMTHEWVEFKGISCRQTCKEPLGFKQFGGANIMILCTPPRVMKRAKFNMYNSHNSSGGMNNTHFGTEPLDRIYMDMWWPPMAHNKDCMFAPFCRCRMRSYHYWDHRMFDLMNHWLEWQPYQTMCDVNDRFVCQPKEWHHRHGNVMGNQYKLMMLLKKWQIRHTMHYDDHEGCQTDPQLAILAKVGEKKTVMAEGQKKNAYLVEHTQNNCCLSKGLSFQAWGTAWRWYLHHPIGQYKNWHWFPAHRMGMGGCKRGLDCEQEYTEHNSILVYLNVFNGEWQWYIINQIQQLHELHLAAHVERSNSAIVVAAMGQTHRHWIRRWDGTEWCGNIKHGIGNMWGNDTPMAWRQSKQDWDEHWNGWMVAMFLKMSEMKNKCLIQCIELGETTGKLEFSWKRDWQKMIAISFMLHKCRWSKESQFR'
    n = 1
    ambiguous_back_table = {}
    for codon, aa in CodonTable.standard_rna_table.forward_table.items():
        if aa in ambiguous_back_table:
            ambiguous_back_table[aa].append(codon)
        else:
            ambiguous_back_table[aa] = [codon]

    for c in protein:
        n = (n * len(ambiguous_back_table[c])) % 1000000
    print(n * 3)
